---
- name: Install required packages
  package:
    name: "{{ package_install }}"
    state: present
  tags:
    - packages

- name: Removing required packages
  package:
    name: "{{ package_remove }}"
    state: absent
  tags:
    - packages
