---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  # stop the build if yamllint fails
  yamllint `git ls-files '*.yaml' '*.yml'`
  # stop the build if there are Python syntax errors or undefined names
  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
platforms:
  - name: debian-10
    image: "ghcr.io/hspaans/molecule-container-debian:10"
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: debian-11
    image: "ghcr.io/hspaans/molecule-container-debian:11"
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: debian-12
    image: "ghcr.io/hspaans/molecule-container-debian:12"
    command: ""
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
  inventory:
    group_vars:
      all:
        package_install:
          - zip
        package_remove:
          - bzip2
verifier:
  name: testinfra
  directory: ../resources/tests/
