---
name: CI

on:
  pull_request:

jobs:

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANSIBLE_DIRECTORY: /
          VALIDATE_ANSIBLE: false

  molecule:
    needs: lint
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - "ansible==2.9.*"
          - "ansible==2.10.*"
        distro:
          - centos:7
          - centos:8
          - debian:9
          - debian:10
          - debian:11
          - fedora:33
          - fedora:34
          - ubuntu:18.04
          - ubuntu:20.04

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install test dependencies
        run: |
          pip3 install ${{ matrix.ansible }} ansible-lint molecule molecule-docker docker flake8 pytest pytest-testinfra

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
